set(PLANTOS_ARCH_DEFAULT "riscv32")
set(PLANTOS_SOC_VENDOR_DEFAULT "espressif")
set(PLANTOS_SOC_DEFAULT "esp32-c6")
set(PLANTOS_BOARD_VENDOR_DEFAULT "waveshare")
set(PLANTOS_BOARD_DEFAULT "esp32-c6-dev-kit-n8")
set(PLANTOS_IMAGE_NAME_DEFAULT "kernel")

if(DEFINED ARCH AND NOT DEFINED PLANTOS_ARCH)
    set(PLANTOS_ARCH "${ARCH}")
endif()

if(DEFINED SOC_VENDOR AND NOT DEFINED PLANTOS_SOC_VENDOR)
    set(PLANTOS_SOC_VENDOR "${SOC_VENDOR}")
endif()

if(DEFINED SOC AND NOT DEFINED PLANTOS_SOC)
    set(PLANTOS_SOC "${SOC}")
endif()

if(DEFINED BOARD_VENDOR AND NOT DEFINED PLANTOS_BOARD_VENDOR)
    set(PLANTOS_BOARD_VENDOR "${BOARD_VENDOR}")
endif()

if(DEFINED BOARD AND NOT DEFINED PLANTOS_BOARD)
    if(NOT DEFINED PLANTOS_BOARD_VENDOR)
        string(REGEX MATCH "^([^-]+)-(.*)$" _plantos_board_match "${BOARD}")
        if(CMAKE_MATCH_1 AND CMAKE_MATCH_2)
            set(PLANTOS_BOARD_VENDOR "${CMAKE_MATCH_1}")
            set(PLANTOS_BOARD "${CMAKE_MATCH_2}")
        else()
            set(PLANTOS_BOARD "${BOARD}")
        endif()
    else()
        set(PLANTOS_BOARD "${BOARD}")
    endif()
endif()

set(_plantos_arch_value "${PLANTOS_ARCH_DEFAULT}")
if(DEFINED PLANTOS_ARCH)
    set(_plantos_arch_value "${PLANTOS_ARCH}")
endif()

set(_plantos_soc_vendor_value "${PLANTOS_SOC_VENDOR_DEFAULT}")
if(DEFINED PLANTOS_SOC_VENDOR)
    set(_plantos_soc_vendor_value "${PLANTOS_SOC_VENDOR}")
endif()

set(_plantos_soc_value "${PLANTOS_SOC_DEFAULT}")
if(DEFINED PLANTOS_SOC)
    set(_plantos_soc_value "${PLANTOS_SOC}")
endif()

set(_plantos_board_vendor_value "${PLANTOS_BOARD_VENDOR_DEFAULT}")
if(DEFINED PLANTOS_BOARD_VENDOR)
    set(_plantos_board_vendor_value "${PLANTOS_BOARD_VENDOR}")
endif()

set(_plantos_board_value "${PLANTOS_BOARD_DEFAULT}")
if(DEFINED PLANTOS_BOARD)
    set(_plantos_board_value "${PLANTOS_BOARD}")
endif()

set(_plantos_image_name_value "${PLANTOS_IMAGE_NAME_DEFAULT}")
if(DEFINED PLANTOS_IMAGE_NAME)
    set(_plantos_image_name_value "${PLANTOS_IMAGE_NAME}")
endif()

set(PLANTOS_ARCH "${_plantos_arch_value}" CACHE STRING "Target architecture")
set(PLANTOS_SOC_VENDOR "${_plantos_soc_vendor_value}" CACHE STRING "Target SoC vendor")
set(PLANTOS_SOC "${_plantos_soc_value}" CACHE STRING "Target SoC")
set(PLANTOS_BOARD_VENDOR "${_plantos_board_vendor_value}" CACHE STRING "Target board vendor")
set(PLANTOS_BOARD "${_plantos_board_value}" CACHE STRING "Target board")
set(PLANTOS_IMAGE_NAME "${_plantos_image_name_value}" CACHE STRING "Final image base name")

set(PLANTOS_RISCV_ISA "rv32imac_zicsr_zifencei" CACHE STRING "RISC-V ISA string")
set(PLANTOS_RISCV_ABI "ilp32" CACHE STRING "RISC-V ABI string")

set_property(CACHE PLANTOS_ARCH PROPERTY STRINGS riscv32)
set_property(CACHE PLANTOS_SOC_VENDOR PROPERTY STRINGS espressif)
set_property(CACHE PLANTOS_SOC PROPERTY STRINGS esp32-c6)
set_property(CACHE PLANTOS_BOARD_VENDOR PROPERTY STRINGS waveshare)
set_property(CACHE PLANTOS_BOARD PROPERTY STRINGS esp32-c6-dev-kit-n8)

set(PLANTOS_ARCH_DIR "${PROJECT_SOURCE_DIR}/src/arch/${PLANTOS_ARCH}")
set(PLANTOS_SOC_DIR "${PROJECT_SOURCE_DIR}/src/platform/soc/${PLANTOS_SOC_VENDOR}/${PLANTOS_SOC}")
set(PLANTOS_BOARD_DIR "${PROJECT_SOURCE_DIR}/src/platform/board/${PLANTOS_BOARD_VENDOR}/${PLANTOS_BOARD}")
set(PLANTOS_LINKER_SCRIPT "${PLANTOS_SOC_DIR}/linker.ld")

foreach(required_path IN ITEMS PLANTOS_ARCH_DIR PLANTOS_SOC_DIR PLANTOS_BOARD_DIR)
    if(NOT IS_DIRECTORY "${${required_path}}")
        message(FATAL_ERROR "Selected target path does not exist: ${${required_path}}")
    endif()
endforeach()

if(NOT EXISTS "${PLANTOS_LINKER_SCRIPT}")
    message(FATAL_ERROR "Selected target linker script does not exist: ${PLANTOS_LINKER_SCRIPT}")
endif()
